#Minecraft server properties
#Thu Jan 30 20:20:09 UTC 2025
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=false
enable-query=false
generator-settings={}
enforce-secure-profile=true
level-name=world
motd=§r              §5§l(MSX)  §dHosting Gratuito§r\n          §f§nhttps\://discord.gg/w9xt8ydNZe
query.port=25565
pvp=true
generate-structures=true
max-chained-neighbor-updates=1000000
difficulty=easy
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=false
use-native-transport=true
max-players=20
online-mode=false
enable-status=true
allow-flight=false
initial-disabled-packs=create_new_age\:create_new_age_monkey_edition,data/SkyVillages-FarmersDelightCompat-1.20.1-1.0.3.zip,data/hardening_catalyst_blacklist.zip,data/Scarecrow_Obliterator.zip,data/SkyVillages-GraveyardCompat-1.20.1-1.0.3.zip,data/ElocinDev-Travelers-Comfort-Datapack.zip,data/SkyVillages-SupplementariesCompat-1.20.1-1.0.3.1.zip,data/WDA-NoFlyingStructures-1.18.2-1.19.2.zip,data/GamerAxeRebalance.zip,data/endrem_apoth_compat.zip,data/simplyswords_join_book.zip,data/BE_default_endgen_fix_1.20.x.zip,data/TrophyAdjustments.zip,data/SkyVillages-PracticalPlushiesCompat-1.20.1-1.0.3.2.zip,data/WDA-VanillaLoot-1.18.2-1.19.2-0.0.1.zip,data/auto_fire_hooks.zip,data/ichphilipp-s-endcity-better-end-1-18-1.zip,data/LessStructures-SpacingTweaks-1.20.1-2.1.56.zip,data/SkyVillages-WaystonesCompat-1.20.1-1.0.3-fabric.zip
broadcast-rcon-to-ops=true
view-distance=10
server-ip=
resource-pack-prompt=
allow-nether=true
server-port=25565
enable-rcon=false
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=10
rcon.password=
player-idle-timeout=0
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
function-permission-level=2
initial-enabled-packs=vanilla,fabric
level-type=bclib\:normal
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
spawn-protection=16
resource-pack-sha1=
max-world-size=29999984
